### ISSUE TITLE
Won't be able to implement export_echo_assembly() in wet lab 

### ISSUE THREAD

**Issue by hainesm6** [LondonBiofoundry/basicsynbio#134]
## Issue

The export_echo_assembly() function will correctly assign multiple wells for a unique clip reaction when the number of assemblies using it are greater than 40. However, it doesn't communicate this to the user meaning the clip reaction source plate might not be correctly assembled.

## Potential solution

- Add `assemblies_per_clip`, `clips_plate` and `assemblies_plate` arguments to the export _csvs() function:
    - The assemblies_per_clip argument works identically to the way it does for the pdf_instructions() function.
    - The clips_plate and assemblies_plate arguments accept platemap.Plate objects and places clip reactions and assemblies in corresponding wells, reporting the well as an additional column in the csv files.
- Call the export_csvs() function from within the export_echo_assembly() function with the appropriate arguments and zip together all of the outputs.

**Comment by Benedict-Carling** [comment]
Hi @hainesm6 

What do you think about adding plate_well_volume, plate_dead_volume and clip_volume_per_reaction instead of assemblies per clip? Using assemblies per clip confuses me a little bit, using only that, I'm not sure how to calculate clip_volume_per_reaction.

Within the input clips plate would this only allow empty (384 plates)? if so, it might be easy to just return the set plate to the user, instead of using an argument, as more code is required for users to initiate a plate themselves.

I think it might be tricky to input the assembly plate as there is a dynamic number of assembly plates depending on the number of assemblies. I could do this if this is what's desired otherwise we could return to the user the list of assembly plates instead somehow. It might again be easier to simply return assembly plates instead of using an argument to avoid users needing to initialise them. I guess it depends how flexible users will be on types of input and if they will gain from having a range of dimensions of clips and assembly plates.

In the case of multiple assembly plates - more than 96 assemblies. How do we plan to report the well of an assembly in the assembly csv? possibly 0-A1, 0-A2,... 1-A1...

Within the zip of the echo instruction, a JSON representation of the clips and assemblies plate map objects, alongside the exported csv's referencing the wells of the the plate map objects, could be one good way of returning the information to the user.

Sorry for so many questions, I'm happy to arrange a meeting tomorrow or whenever you're free to clear everything up!

**Comment by hainesm6** [comment]
Hi @Benedict-Carling. Shall we have a chat about this tomorrow? I'm in the lab but should have some incubation time to chat. Let me know when you're available.

**Comment by Benedict-Carling** [comment]
Hi @hainesm6 I can do any time that not 5-6pm 👍

**Comment by hainesm6** [comment]
I tried calling Benedict but it said you were unavailable. I'm free for the next 30 min if you've got time. Otherwise, might be after 6 pm if that's Ok with you?

**Comment by Benedict-Carling** [comment]
details from call, stick with assemblies_per_clip, try to be flexible with plate_size allowing many different plate sizes, 96 may be preferable is the user doesn't have a echo robot, well column added to clips.csv and assemblies.csv is sufficient feedback
